version: "3"

services:
  graphql_typescript_server:
    container_name: graphql_typescript_server
    image: nick3141/graphql-typescript-server:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    volumes:
      - ./_v_logs:/usr/src/app/storage/logs
    networks:
      - nk


networks:
  nk:
    driver: bridge
